QA_PAIRS = [
    {"question": "What is Aetheria Cloud OS?", "answer": "A distributed, cloud-native operating system designed for extreme scalability and low-latency edge computing."},
    {"question": "When was Aetheria launched and by whom?", "answer": "Launched in 2024 by Zenith Systems."},
    {"question": "What is the name of Aetheria's microkernel?", "answer": "Nucleus-Q."},
    {"question": "In what language is the Nucleus-Q microkernel written?", "answer": "Rust."},
    {"question": "What are the four primary functions of Nucleus-Q?", "answer": "Process scheduling, memory management, inter-process communication (IPC), and hardware abstraction."},
    {"question": "How do file systems and network stacks run in Aetheria?", "answer": "They run in user space as isolated 'Service Pods'."},
    {"question": "What is 'Fluid Memory'?", "answer": "A technique allowing nodes in a cluster to share physical RAM over a 400Gbps InfiniBand link."},
    {"question": "By what percentage does Fluid Memory reduce OOM errors?", "answer": "85%."},
    {"question": "What protocol does the Nebula-X network stack support?", "answer": "Zero-Trust Mesh protocol."},
    {"question": "What encryption is used for packets in Nebula-X?", "answer": "AES-256-GCM at the hardware level."},
    {"question": "What is the name of the congestion control algorithm in Nebula-X?", "answer": "Solaris."},
    {"question": "What is the default file system for Aetheria?", "answer": "Chronos-FS."},
    {"question": "Does Chronos-FS support immutable data?", "answer": "Yes, it is a log-structured, immutable file system."},
    {"question": "What is 'Time-Travel Recovery' in Chronos-FS?", "answer": "A feature supported by instantaneous snapshots for data recovery."},
    {"question": "What is the maximum file size supported by Chronos-FS?", "answer": "1 Yottabyte."},
    {"question": "How is deduplication handled in Chronos-FS?", "answer": "Inline and hardware-accelerated."},
    {"question": "What does the Aegis layer provide?", "answer": "PII (Personally Identifiable Information) masking by default."},
    {"question": "What hashing algorithm is used for the 'Sensitive' zone?", "answer": "SHA-3."},
    {"question": "What is the Root of Trust for Aetheria?", "answer": "Hardware Security Module (HSM) 4.0."},
    {"question": "What is 'Flux-Lang'?", "answer": "A domain-specific language for building reactive microservices."},
    {"question": "What is the name of the compiler for Flux-Lang?", "answer": "Aether-C."},
    {"question": "Which IDE is recommended for Aetheria development?", "answer": "Zenith Studio."},
    {"question": "What is the package manager for Aetheria?", "answer": "A-Pkg."},
    {"question": "How much faster is Aetheria at context switching compared to Linux 6.5?", "answer": "30% faster."},
    {"question": "What was the improvement in database tail latency?", "answer": "50% lower tail latency."},
    {"question": "What is the throughput improvement for video transcoding?", "answer": "20% higher throughput."},
    {"question": "Under what license is Aetheria available?", "answer": "Zenith Open Business License (ZOBL)."},
    {"question": "Who can use Aetheria for free?", "answer": "Individuals."},
    {"question": "What is the revenue threshold for a paid subscription?", "answer": "$5M USD."},
    {"question": "Which processor architectures are compatible with Aetheria?", "answer": "x86_64, ARMv9, and RISC-V 'Titan'."},
    {"question": "What is the minimum RAM requirement for Aetheria?", "answer": "2GB RAM."},
    {"question": "What is the minimum storage requirement for Aetheria?", "answer": "10GB storage."},
    {"question": "What link speed is used by Fluid Memory?", "answer": "400Gbps InfiniBand link."},
    {"question": "Is the Solaris algorithm optimized for satellite links?", "answer": "Yes, it optimizes for satellite-to-ground links."},
    {"question": "What is the block size range for Chronos-FS?", "answer": "4KB to 1MB (Dynamic)."},
    {"question": "Is Chronos-FS log-structured?", "answer": "Yes."},
    {"question": "Does Aegis hash data in the Sensitive zone?", "answer": "Yes, it hashes it using SHA-3."},
    {"question": "What type of biometric handshake is used for authentication?", "answer": "Multi-factor biometric handshake."},
    {"question": "Is Zenith Systems the developer of Aetheria?", "answer": "Yes."},
    {"question": "What architecture does Aetheria use?", "answer": "Microkernel architecture."},
    {"question": "What is the role of Service Pods?", "answer": "They run isolated services like file systems and network stacks in user space."},
    {"question": "Can Aetheria share physical RAM across nodes?", "answer": "Yes, through Fluid Memory."},
    {"question": "What does AES-256-GCM protect in Aetheria?", "answer": "Network packets in the Nebula-X stack."},
    {"question": "Does Aetheria support RISC-V?", "answer": "Yes, specifically the 'Titan' processors."},
    {"question": "Is A-Pkg the name of the package manager?", "answer": "Yes."},
    {"question": "What version of Linux was Aetheria benchmarked against?", "answer": "Linux 6.5."},
    {"question": "What is Zenith Studio used for?", "answer": "It is an IDE for Aetheria development."},
    {"question": "What is the primary goal of the Nucleus-Q microkernel?", "answer": "Memory safety and minimal core functions."},
    {"question": "Is Aetheria cloud-native?", "answer": "Yes."},
    {"question": "Does Aetheria use HSM for security?", "answer": "Yes, HSM 4.0."}
]
